// Generated by gencpp from file franka_action_lib/ExecuteSkillResult.msg
// DO NOT EDIT!


#ifndef FRANKA_ACTION_LIB_MESSAGE_EXECUTESKILLRESULT_H
#define FRANKA_ACTION_LIB_MESSAGE_EXECUTESKILLRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_action_lib
{
template <class ContainerAllocator>
struct ExecuteSkillResult_
{
  typedef ExecuteSkillResult_<ContainerAllocator> Type;

  ExecuteSkillResult_()
    : num_execution_result(0)
    , execution_result()  {
    }
  ExecuteSkillResult_(const ContainerAllocator& _alloc)
    : num_execution_result(0)
    , execution_result(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _num_execution_result_type;
  _num_execution_result_type num_execution_result;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _execution_result_type;
  _execution_result_type execution_result;





  typedef boost::shared_ptr< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteSkillResult_

typedef ::franka_action_lib::ExecuteSkillResult_<std::allocator<void> > ExecuteSkillResult;

typedef boost::shared_ptr< ::franka_action_lib::ExecuteSkillResult > ExecuteSkillResultPtr;
typedef boost::shared_ptr< ::franka_action_lib::ExecuteSkillResult const> ExecuteSkillResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace franka_action_lib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'franka_action_lib': ['/home/klz1/Documents/robot-interface/catkin_ws/src/franka_action_lib/msg', '/home/klz1/Documents/robot-interface/catkin_ws/devel/share/franka_action_lib/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e8c8c9251bae079bb7afe77bb20cd8c";
  }

  static const char* value(const ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e8c8c9251bae079ULL;
  static const uint64_t static_value2 = 0xbb7afe77bb20cd8cULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_action_lib/ExecuteSkillResult";
  }

  static const char* value(const ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result - happens when the skill terminates\n\
uint64 num_execution_result\n\
float64[] execution_result\n\
";
  }

  static const char* value(const ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_execution_result);
      stream.next(m.execution_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteSkillResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_action_lib::ExecuteSkillResult_<ContainerAllocator>& v)
  {
    s << indent << "num_execution_result: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.num_execution_result);
    s << indent << "execution_result[]" << std::endl;
    for (size_t i = 0; i < v.execution_result.size(); ++i)
    {
      s << indent << "  execution_result[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.execution_result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_ACTION_LIB_MESSAGE_EXECUTESKILLRESULT_H
