// Generated by gencpp from file franka_action_lib/ExecuteSkillActionGoal.msg
// DO NOT EDIT!


#ifndef FRANKA_ACTION_LIB_MESSAGE_EXECUTESKILLACTIONGOAL_H
#define FRANKA_ACTION_LIB_MESSAGE_EXECUTESKILLACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <franka_action_lib/ExecuteSkillGoal.h>

namespace franka_action_lib
{
template <class ContainerAllocator>
struct ExecuteSkillActionGoal_
{
  typedef ExecuteSkillActionGoal_<ContainerAllocator> Type;

  ExecuteSkillActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ExecuteSkillActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::franka_action_lib::ExecuteSkillGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteSkillActionGoal_

typedef ::franka_action_lib::ExecuteSkillActionGoal_<std::allocator<void> > ExecuteSkillActionGoal;

typedef boost::shared_ptr< ::franka_action_lib::ExecuteSkillActionGoal > ExecuteSkillActionGoalPtr;
typedef boost::shared_ptr< ::franka_action_lib::ExecuteSkillActionGoal const> ExecuteSkillActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace franka_action_lib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'franka_action_lib': ['/home/klz1/Documents/robot-interface/catkin_ws/src/franka_action_lib/msg', '/home/klz1/Documents/robot-interface/catkin_ws/devel/share/franka_action_lib/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0391d71d2c0efd872aba732bd458f1c1";
  }

  static const char* value(const ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0391d71d2c0efd87ULL;
  static const uint64_t static_value2 = 0x2aba732bd458f1c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_action_lib/ExecuteSkillActionGoal";
  }

  static const char* value(const ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
ExecuteSkillGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: franka_action_lib/ExecuteSkillGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int64 skill_type\n\
string skill_description\n\
int64 meta_skill_type\n\
int64 meta_skill_id\n\
\n\
# Sensor topic to subscribe to\n\
string[] sensor_topics\n\
uint64[] sensor_value_sizes\n\
float64[] initial_sensor_values\n\
\n\
# traj gen\n\
int64 traj_gen_type\n\
uint64 num_traj_gen_params\n\
float64[] traj_gen_params\n\
\n\
# fbc\n\
int64 feedback_controller_type\n\
uint64 num_feedback_controller_params\n\
float64[] feedback_controller_params\n\
\n\
# termination\n\
int64 termination_type\n\
uint64 num_termination_params\n\
float64[] termination_params \n\
\n\
# timer\n\
int64 timer_type\n\
uint64 num_timer_params\n\
float64[] timer_params\n\
";
  }

  static const char* value(const ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteSkillActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_action_lib::ExecuteSkillActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::franka_action_lib::ExecuteSkillGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_ACTION_LIB_MESSAGE_EXECUTESKILLACTIONGOAL_H
