// Generated by gencpp from file franka_action_lib/GetCurrentRobolibStatusCmdResponse.msg
// DO NOT EDIT!


#ifndef FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOLIBSTATUSCMDRESPONSE_H
#define FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOLIBSTATUSCMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <franka_action_lib/RobolibStatus.h>

namespace franka_action_lib
{
template <class ContainerAllocator>
struct GetCurrentRobolibStatusCmdResponse_
{
  typedef GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> Type;

  GetCurrentRobolibStatusCmdResponse_()
    : robolib_status()  {
    }
  GetCurrentRobolibStatusCmdResponse_(const ContainerAllocator& _alloc)
    : robolib_status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::franka_action_lib::RobolibStatus_<ContainerAllocator>  _robolib_status_type;
  _robolib_status_type robolib_status;





  typedef boost::shared_ptr< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetCurrentRobolibStatusCmdResponse_

typedef ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<std::allocator<void> > GetCurrentRobolibStatusCmdResponse;

typedef boost::shared_ptr< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse > GetCurrentRobolibStatusCmdResponsePtr;
typedef boost::shared_ptr< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse const> GetCurrentRobolibStatusCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace franka_action_lib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'franka_action_lib': ['/home/klz1/Documents/robot-interface/catkin_ws/src/franka_action_lib/msg', '/home/klz1/Documents/robot-interface/catkin_ws/devel/share/franka_action_lib/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a8606837e9f22dc33518a29b863eeb4";
  }

  static const char* value(const ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a8606837e9f22dcULL;
  static const uint64_t static_value2 = 0x33518a29b863eeb4ULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_action_lib/GetCurrentRobolibStatusCmdResponse";
  }

  static const char* value(const ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RobolibStatus robolib_status\n\
\n\
================================================================================\n\
MSG: franka_action_lib/RobolibStatus\n\
# Franka robot state\n\
std_msgs/Header header\n\
bool is_ready\n\
string error_description\n\
bool is_fresh\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robolib_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCurrentRobolibStatusCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_action_lib::GetCurrentRobolibStatusCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "robolib_status: ";
    s << std::endl;
    Printer< ::franka_action_lib::RobolibStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.robolib_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOLIBSTATUSCMDRESPONSE_H
