// Generated by gencpp from file franka_action_lib/GetCurrentRobotStateCmdRequest.msg
// DO NOT EDIT!


#ifndef FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOTSTATECMDREQUEST_H
#define FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOTSTATECMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_action_lib
{
template <class ContainerAllocator>
struct GetCurrentRobotStateCmdRequest_
{
  typedef GetCurrentRobotStateCmdRequest_<ContainerAllocator> Type;

  GetCurrentRobotStateCmdRequest_()
    {
    }
  GetCurrentRobotStateCmdRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCurrentRobotStateCmdRequest_

typedef ::franka_action_lib::GetCurrentRobotStateCmdRequest_<std::allocator<void> > GetCurrentRobotStateCmdRequest;

typedef boost::shared_ptr< ::franka_action_lib::GetCurrentRobotStateCmdRequest > GetCurrentRobotStateCmdRequestPtr;
typedef boost::shared_ptr< ::franka_action_lib::GetCurrentRobotStateCmdRequest const> GetCurrentRobotStateCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace franka_action_lib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'franka_action_lib': ['/home/klz1/Documents/robot-interface/catkin_ws/src/franka_action_lib/msg', '/home/klz1/Documents/robot-interface/catkin_ws/devel/share/franka_action_lib/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_action_lib/GetCurrentRobotStateCmdRequest";
  }

  static const char* value(const ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCurrentRobotStateCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::franka_action_lib::GetCurrentRobotStateCmdRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOTSTATECMDREQUEST_H
