// Generated by gencpp from file franka_action_lib/GetCurrentRobolibStatusCmd.msg
// DO NOT EDIT!


#ifndef FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOLIBSTATUSCMD_H
#define FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOLIBSTATUSCMD_H

#include <ros/service_traits.h>


#include <franka_action_lib/GetCurrentRobolibStatusCmdRequest.h>
#include <franka_action_lib/GetCurrentRobolibStatusCmdResponse.h>


namespace franka_action_lib
{

struct GetCurrentRobolibStatusCmd
{

typedef GetCurrentRobolibStatusCmdRequest Request;
typedef GetCurrentRobolibStatusCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentRobolibStatusCmd
} // namespace franka_action_lib


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_action_lib::GetCurrentRobolibStatusCmd > {
  static const char* value()
  {
    return "4a8606837e9f22dc33518a29b863eeb4";
  }

  static const char* value(const ::franka_action_lib::GetCurrentRobolibStatusCmd&) { return value(); }
};

template<>
struct DataType< ::franka_action_lib::GetCurrentRobolibStatusCmd > {
  static const char* value()
  {
    return "franka_action_lib/GetCurrentRobolibStatusCmd";
  }

  static const char* value(const ::franka_action_lib::GetCurrentRobolibStatusCmd&) { return value(); }
};


// service_traits::MD5Sum< ::franka_action_lib::GetCurrentRobolibStatusCmdRequest> should match 
// service_traits::MD5Sum< ::franka_action_lib::GetCurrentRobolibStatusCmd > 
template<>
struct MD5Sum< ::franka_action_lib::GetCurrentRobolibStatusCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_action_lib::GetCurrentRobolibStatusCmd >::value();
  }
  static const char* value(const ::franka_action_lib::GetCurrentRobolibStatusCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_action_lib::GetCurrentRobolibStatusCmdRequest> should match 
// service_traits::DataType< ::franka_action_lib::GetCurrentRobolibStatusCmd > 
template<>
struct DataType< ::franka_action_lib::GetCurrentRobolibStatusCmdRequest>
{
  static const char* value()
  {
    return DataType< ::franka_action_lib::GetCurrentRobolibStatusCmd >::value();
  }
  static const char* value(const ::franka_action_lib::GetCurrentRobolibStatusCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse> should match 
// service_traits::MD5Sum< ::franka_action_lib::GetCurrentRobolibStatusCmd > 
template<>
struct MD5Sum< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_action_lib::GetCurrentRobolibStatusCmd >::value();
  }
  static const char* value(const ::franka_action_lib::GetCurrentRobolibStatusCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse> should match 
// service_traits::DataType< ::franka_action_lib::GetCurrentRobolibStatusCmd > 
template<>
struct DataType< ::franka_action_lib::GetCurrentRobolibStatusCmdResponse>
{
  static const char* value()
  {
    return DataType< ::franka_action_lib::GetCurrentRobolibStatusCmd >::value();
  }
  static const char* value(const ::franka_action_lib::GetCurrentRobolibStatusCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOLIBSTATUSCMD_H
