// Generated by gencpp from file franka_action_lib/GetCurrentRobotStateCmd.msg
// DO NOT EDIT!


#ifndef FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOTSTATECMD_H
#define FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOTSTATECMD_H

#include <ros/service_traits.h>


#include <franka_action_lib/GetCurrentRobotStateCmdRequest.h>
#include <franka_action_lib/GetCurrentRobotStateCmdResponse.h>


namespace franka_action_lib
{

struct GetCurrentRobotStateCmd
{

typedef GetCurrentRobotStateCmdRequest Request;
typedef GetCurrentRobotStateCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentRobotStateCmd
} // namespace franka_action_lib


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_action_lib::GetCurrentRobotStateCmd > {
  static const char* value()
  {
    return "9d11d5ba31b9f0ae529e9a5c66e25ee4";
  }

  static const char* value(const ::franka_action_lib::GetCurrentRobotStateCmd&) { return value(); }
};

template<>
struct DataType< ::franka_action_lib::GetCurrentRobotStateCmd > {
  static const char* value()
  {
    return "franka_action_lib/GetCurrentRobotStateCmd";
  }

  static const char* value(const ::franka_action_lib::GetCurrentRobotStateCmd&) { return value(); }
};


// service_traits::MD5Sum< ::franka_action_lib::GetCurrentRobotStateCmdRequest> should match 
// service_traits::MD5Sum< ::franka_action_lib::GetCurrentRobotStateCmd > 
template<>
struct MD5Sum< ::franka_action_lib::GetCurrentRobotStateCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_action_lib::GetCurrentRobotStateCmd >::value();
  }
  static const char* value(const ::franka_action_lib::GetCurrentRobotStateCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_action_lib::GetCurrentRobotStateCmdRequest> should match 
// service_traits::DataType< ::franka_action_lib::GetCurrentRobotStateCmd > 
template<>
struct DataType< ::franka_action_lib::GetCurrentRobotStateCmdRequest>
{
  static const char* value()
  {
    return DataType< ::franka_action_lib::GetCurrentRobotStateCmd >::value();
  }
  static const char* value(const ::franka_action_lib::GetCurrentRobotStateCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_action_lib::GetCurrentRobotStateCmdResponse> should match 
// service_traits::MD5Sum< ::franka_action_lib::GetCurrentRobotStateCmd > 
template<>
struct MD5Sum< ::franka_action_lib::GetCurrentRobotStateCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_action_lib::GetCurrentRobotStateCmd >::value();
  }
  static const char* value(const ::franka_action_lib::GetCurrentRobotStateCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_action_lib::GetCurrentRobotStateCmdResponse> should match 
// service_traits::DataType< ::franka_action_lib::GetCurrentRobotStateCmd > 
template<>
struct DataType< ::franka_action_lib::GetCurrentRobotStateCmdResponse>
{
  static const char* value()
  {
    return DataType< ::franka_action_lib::GetCurrentRobotStateCmd >::value();
  }
  static const char* value(const ::franka_action_lib::GetCurrentRobotStateCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_ACTION_LIB_MESSAGE_GETCURRENTROBOTSTATECMD_H
