// Generated by gencpp from file franka_action_lib/RobolibStatus.msg
// DO NOT EDIT!


#ifndef FRANKA_ACTION_LIB_MESSAGE_ROBOLIBSTATUS_H
#define FRANKA_ACTION_LIB_MESSAGE_ROBOLIBSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace franka_action_lib
{
template <class ContainerAllocator>
struct RobolibStatus_
{
  typedef RobolibStatus_<ContainerAllocator> Type;

  RobolibStatus_()
    : header()
    , is_ready(false)
    , error_description()
    , is_fresh(false)  {
    }
  RobolibStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_ready(false)
    , error_description(_alloc)
    , is_fresh(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_ready_type;
  _is_ready_type is_ready;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_description_type;
  _error_description_type error_description;

   typedef uint8_t _is_fresh_type;
  _is_fresh_type is_fresh;





  typedef boost::shared_ptr< ::franka_action_lib::RobolibStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_action_lib::RobolibStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobolibStatus_

typedef ::franka_action_lib::RobolibStatus_<std::allocator<void> > RobolibStatus;

typedef boost::shared_ptr< ::franka_action_lib::RobolibStatus > RobolibStatusPtr;
typedef boost::shared_ptr< ::franka_action_lib::RobolibStatus const> RobolibStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_action_lib::RobolibStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_action_lib::RobolibStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace franka_action_lib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'franka_action_lib': ['/home/klz1/Documents/robot-interface/catkin_ws/src/franka_action_lib/msg', '/home/klz1/Documents/robot-interface/catkin_ws/devel/share/franka_action_lib/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::franka_action_lib::RobolibStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_action_lib::RobolibStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_action_lib::RobolibStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_action_lib::RobolibStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_action_lib::RobolibStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_action_lib::RobolibStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_action_lib::RobolibStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3b55f2e82de58761423a010b7b229a0";
  }

  static const char* value(const ::franka_action_lib::RobolibStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3b55f2e82de5876ULL;
  static const uint64_t static_value2 = 0x1423a010b7b229a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_action_lib::RobolibStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_action_lib/RobolibStatus";
  }

  static const char* value(const ::franka_action_lib::RobolibStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_action_lib::RobolibStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Franka robot state\n\
std_msgs/Header header\n\
bool is_ready\n\
string error_description\n\
bool is_fresh\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::franka_action_lib::RobolibStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_action_lib::RobolibStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_ready);
      stream.next(m.error_description);
      stream.next(m.is_fresh);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobolibStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_action_lib::RobolibStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_action_lib::RobolibStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_ready);
    s << indent << "error_description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_description);
    s << indent << "is_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_fresh);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_ACTION_LIB_MESSAGE_ROBOLIBSTATUS_H
