(cl:defpackage franka_action_lib-srv
  (:use )
  (:export
   "GETCURRENTROBOLIBSTATUSCMD"
   "<GETCURRENTROBOLIBSTATUSCMD-REQUEST>"
   "GETCURRENTROBOLIBSTATUSCMD-REQUEST"
   "<GETCURRENTROBOLIBSTATUSCMD-RESPONSE>"
   "GETCURRENTROBOLIBSTATUSCMD-RESPONSE"
   "GETCURRENTROBOTSTATECMD"
   "<GETCURRENTROBOTSTATECMD-REQUEST>"
   "GETCURRENTROBOTSTATECMD-REQUEST"
   "<GETCURRENTROBOTSTATECMD-RESPONSE>"
   "GETCURRENTROBOTSTATECMD-RESPONSE"
  ))

