# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from franka_action_lib/GetCurrentRobolibStatusCmdRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetCurrentRobolibStatusCmdRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "franka_action_lib/GetCurrentRobolibStatusCmdRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetCurrentRobolibStatusCmdRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from franka_action_lib/GetCurrentRobolibStatusCmdResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import franka_action_lib.msg
import std_msgs.msg

class GetCurrentRobolibStatusCmdResponse(genpy.Message):
  _md5sum = "4a8606837e9f22dc33518a29b863eeb4"
  _type = "franka_action_lib/GetCurrentRobolibStatusCmdResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """RobolibStatus robolib_status

================================================================================
MSG: franka_action_lib/RobolibStatus
# Franka robot state
std_msgs/Header header
bool is_ready
string error_description
bool is_fresh
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['robolib_status']
  _slot_types = ['franka_action_lib/RobolibStatus']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robolib_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetCurrentRobolibStatusCmdResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.robolib_status is None:
        self.robolib_status = franka_action_lib.msg.RobolibStatus()
    else:
      self.robolib_status = franka_action_lib.msg.RobolibStatus()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.robolib_status.header.seq, _x.robolib_status.header.stamp.secs, _x.robolib_status.header.stamp.nsecs))
      _x = self.robolib_status.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.robolib_status.is_ready))
      _x = self.robolib_status.error_description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.robolib_status.is_fresh))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.robolib_status is None:
        self.robolib_status = franka_action_lib.msg.RobolibStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.robolib_status.header.seq, _x.robolib_status.header.stamp.secs, _x.robolib_status.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robolib_status.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.robolib_status.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.robolib_status.is_ready,) = _get_struct_B().unpack(str[start:end])
      self.robolib_status.is_ready = bool(self.robolib_status.is_ready)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robolib_status.error_description = str[start:end].decode('utf-8')
      else:
        self.robolib_status.error_description = str[start:end]
      start = end
      end += 1
      (self.robolib_status.is_fresh,) = _get_struct_B().unpack(str[start:end])
      self.robolib_status.is_fresh = bool(self.robolib_status.is_fresh)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.robolib_status.header.seq, _x.robolib_status.header.stamp.secs, _x.robolib_status.header.stamp.nsecs))
      _x = self.robolib_status.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.robolib_status.is_ready))
      _x = self.robolib_status.error_description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.robolib_status.is_fresh))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.robolib_status is None:
        self.robolib_status = franka_action_lib.msg.RobolibStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.robolib_status.header.seq, _x.robolib_status.header.stamp.secs, _x.robolib_status.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robolib_status.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.robolib_status.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.robolib_status.is_ready,) = _get_struct_B().unpack(str[start:end])
      self.robolib_status.is_ready = bool(self.robolib_status.is_ready)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robolib_status.error_description = str[start:end].decode('utf-8')
      else:
        self.robolib_status.error_description = str[start:end]
      start = end
      end += 1
      (self.robolib_status.is_fresh,) = _get_struct_B().unpack(str[start:end])
      self.robolib_status.is_fresh = bool(self.robolib_status.is_fresh)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class GetCurrentRobolibStatusCmd(object):
  _type          = 'franka_action_lib/GetCurrentRobolibStatusCmd'
  _md5sum = '4a8606837e9f22dc33518a29b863eeb4'
  _request_class  = GetCurrentRobolibStatusCmdRequest
  _response_class = GetCurrentRobolibStatusCmdResponse
